name: Run pytest with Poetry and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-root
          poetry run pip install coverage

      - name: Run pytest with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage html

      - name: Publish coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./htmlcov

      - name: Generate coverage badge
        run: |
          poetry run coverage-badge -o coverage.svg --query=total
          echo "coverage-badge: ${{ env.GITHUB_WORKSPACE }}/coverage.svg" >> $GITHUB_ENV

      - name: Commit and push coverage badge
        run: |
          git checkout $GITHUB_REF
          git add coverage.svg
          git commit -m "Update coverage badge"
          git push
